#!/usr/bin/env php
<?php

declare(strict_types=1);

$path = __DIR__ . '/../../data/repositories.xml';
$xml = simplexml_load_string(file_get_contents($path));

/** @var SimpleXMLElement[] $phars */
$aliases = [];
foreach ($xml->children() as $phar) {
    $aliases[] = (string) $phar->attributes()['alias'];
}

$currentAliases = $aliases;
sort($aliases);

if ($currentAliases != $aliases) {
    fwrite(STDOUT, 'Repositories are not ordered properly:' . PHP_EOL);
    foreach ($aliases as $index => $alias) {
        if ($alias !== $currentAliases[$index]) {
            fwrite(
                STDOUT,
                ' - expected \'' . $alias . '\' got \'' . $currentAliases[$index] . '\'' . PHP_EOL
            );
            exit(1);
        }
    }
}
fwrite(STDOUT, 'Repositories are ordered properly' . PHP_EOL);
exit(0);
