name: Automated Testing

on:
  push:

permissions:
  contents: read

jobs:
  order-repos:
    name: Check ordering of repositories
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - uses: actions/checkout@v4

      - name: Check ordering of repositories
        run: php scripts/order-repos/check
